language: php

sudo: false

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - hhvm

install:
  - composer install --prefer-source

before_script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi

script:
  - phpunit $PHPUNIT_FLAGS

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/test-reporter; fi