version: "3"
services:
  web:
    build: .
    container_name: customerio_web
    ports:
      - "80:80"
      - "443:443"
      - "10001:9000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/var/www/site
    command: ['./vendor/bin/phpunit']

  composer:
    image: library/composer:latest
    container_name: customerio_composer
    volumes:
    - .:/app
    user: 1000:1000
    command: ["install"]